name: Update Submissions

on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * 0"

jobs:
  update-submissions:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.4

      - name: Configure Git
        run: |
          git config user.name "Yuiki Saito"
          git config user.email "yuikisaito@ysaito.win"

      - name: Install plugin
        run: |
          pixi run nu -c "plugin add nu_plugin_query"

      - name: Use plugin
        run: |
          pixi run nu -c "plugin use query"

      - name: Run update-submissions
        run: pixi run update-submissions
